name: flutter_avataaar
description: Flutter wrapper widget for Avataaars API allowing to generate and display avatar images.
repository: https://github.com/frananleo/flutter_avataaar
version: 0.1.14
environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.2.3
  flutter_material_pickers: ^3.6.0
  flutter_svg: ^2.0.7
  http: ^1.1.0
  uuid: ^4.0.0-beta3-1
  universal_io: ^2.2.2
  path_provider: ^2.0.15

dev_dependencies:
  lints: ^2.1.1

flutter:
  assets:
    - lib/assets/translations/
    - lib/assets/svg/